### ISSUE TITLE
Please use semantic versioning

### ISSUE THREAD

**Issue by petercolberg** [mitchellh/go-wordwrap#4]
Please use semantic versioning:

- http://semver.org/
- https://en.wikipedia.org/wiki/Software_versioning
- https://wiki.debian.org/UpstreamGuide#Releases_and_Versions

**Comment by mitchellh** [comment]
The standard Go tooling doesn't provide a way to make use of versioning for dependencies. If it did, I'd most definitely use some versioning scheme. Since it doesn't, there is no real use. 

The Go way currently is to simply never break BC. We've never broken backwards compatibility and don't plan to. I have some libraries still in very active use in almost all HashiCorp tooling and I haven't broken BC in 4 years.

**Comment by petercolberg** [comment]
Hi @mitchellh, thanks for the quick response! I appreciate that you have never broken backwards-compatibility in the past, but there is no reason to assume that would not prove useful in the future.

In fact, standard Go tooling provides a way to make use of versioning to some extent. When importing your package as `gopkg.in/mitchellh/go-wordwrap.v1`, the [gopkg.in](https://gopkg.in) redirection service will fetch the latest tag `v1.Y.Z` for the given major version `v1`.

**Comment by petercolberg** [comment]
Debian packages each Go package repository as a separate Debian source package. In this case, your package has been [included in Debian](https://packages.debian.org/sid/golang-github-mitchellh-go-wordwrap-dev) as a dependency of [acmetool](https://github.com/hlandau/acme). The version of a Debian package includes an upstream part (e.g. "1.0.0") and a Debian part (e.g. "-1"). If an upstream author does not tag releases, we need to make up an upstream version number based on the git commit and date, which yields unwieldy versions that are cumbersome to compare. 

All you would have to do is regularly tag releases, which yields handy Debian package versions and makes it easy to automatically [notice new upstream releases](https://tracker.debian.org/pkg/golang-gopkg-tylerb-graceful.v1) using the Debian package tracker.
